import {
  Box,
  Grid,
  Text,
  GridItem,
  Heading,
  Button,
  DarkMode,
} from "@chakra-ui/react";
import React from "react";
import "./success.css";
import { NavLink } from "react-router-dom";
import Fotter from "../Fotter/Fotter";
import Cards from "../Cards/Cards";

export default function Success() {
  return (
    <>
      <Grid
        pt={200}
        templateColumns="repeat(3, 1fr)"
        gap={{
          base: "0",
          md: "3",
          lg: "6",
        }}
        // border="4px"
        height={"100%"}
      >
        <Grid
          templateColumns="repeat(4, 1fr)"
          m={14}
          gap={1}
          className="hideComponents"
          h={"200"}
        >
          <GridItem
            w="100%"
            h="20"
            bgGradient="linear(to-r, gray.300, yellow.400, pink.200)"
          />
          <GridItem w="85%" h="100%" bg="blue.900" borderRadius={200} />
          <GridItem w="100%" h="20" bg="white.100" />
          <GridItem w="100%" h="20" bg="yellow.300" borderTopLeftRadius={200} />
          {/* part 1 */}
          <GridItem
            w="100%"
            h="20"
            bgGradient="linear(to-r, red.500, yellow.500)"
          />
          <GridItem
            w="100%"
            h="20"
            bg="green.500"
            borderInlineStartRadius={200}
          />
          <GridItem w="100%" h="20" bg="blue.500" />
          <GridItem
            w="90%"
            h="20"
            bgGradient="linear(to-r, blue.300, green.400, red.200)"
            borderRadius={200}
          />
          {/* part 2 */}
          <GridItem
            w="100%"
            h="20"
            bgGradient={[
              "linear(to-tr, teal.300, green.400)",
              "linear(to-t, yellow.200, teal.500)",
              "linear(to-b, orange.100, blue.300)",
            ]}
          />
          <GridItem w="90%" h="20" bg="yellow.300" borderRadius={200} />
          <GridItem
            w="100%"
            h="20"
            bgGradient="linear(to-l, #7928CA, #FF0080)"
          />
          <GridItem w="100%" h="20" bg="red.300" borderEndRadius={200} />
          {/* part 3 */}
          <GridItem
            w="90%"
            h="20"
            bgGradient="linear(to-r, blue.500, green.500)"
            borderRadius={200}
          />
          <GridItem w="100%" h="20" bg="blue.500" />
          <GridItem
            w="100%"
            h="20"
            bgGradient={[
              "linear(to-tr, teal.300, yellow.400)",
              "linear(to-t, blue.200, teal.500)",
              "linear(to-b, orange.100, purple.300)",
            ]}
            borderBottomRightRadius={50}
          />
          <GridItem w="100%" h="20" bg="orange.500" />
          {/* part 4 */}
          <GridItem
            w="100%"
            h="20"
            bgGradient="linear(to-r, green.200, pink.500)"
          />
          <GridItem w="100%" h="20" bg="green.200" />
          <GridItem w="90%" h="20" bg="blue.500" borderRadius={200} />
          <GridItem
            w="100%"
            h="20"
            bgGradient="linear(to-r, red.200, yellow.500)"
            borderTopEndRadius={100}
          />
          {/* part 5 */}
        </Grid>
        {/* gird part 2 of the website  */}
        <Box textAlign={"center"} mt={20} width={"100%"} className="Aftereight">
          <Text
            fontSize="2xl"
            // m={20}
            bgGradient="linear(to-l, #7928CA, #FF0080) "
            bgClip="text"
            as={"b"}
          >
            SUCCESS STORIES
          </Text>
          <Heading
            as="h2"
            size="3xl"
            noOfLines={3}
            m="5"
            lineHeight={"shorter"}
          >
            Trusted by Top Outbound Teams
          </Heading>
          <Text fontSize="xl" lineHeight={"short"}>
            Millions of dollars in revenue have been generated by sales teams
            that use LeadIQ to streamline their prospecting efforts.
          </Text>
          <NavLink to={"/demo"}>
            <DarkMode>
              <Button
                colorScheme="green"
                borderRadius={50}
                h={70}
                w={200}
                fontSize={"xl"}
                m="10"
              >
                Book Demo
              </Button>
            </DarkMode>
          </NavLink>
        </Box>
        {/* text section has to been put here. */}
        <Grid templateColumns="repeat(4, 1fr)" gap={1} m={14} h={"200"}>
          <GridItem
            w="100%"
            h="20"
            bgGradient="linear(to-r, gray.300, yellow.400, pink.200)"
          />
          <GridItem w="100%" h="20" bg="green.200" />
          <GridItem w="100%" h="20" bg="blue.500" />
          <GridItem w="90%" h="20" bg="blue.500" borderRadius={200} />
          <GridItem
            w="100%"
            h="20"
            bgGradient={[
              "linear(to-tr, teal.300, yellow.400)",
              "linear(to-t, blue.200, teal.500)",
              "linear(to-b, orange.100, purple.300)",
            ]}
          />
          <GridItem
            w="100%"
            h="20"
            bgGradient="linear(to-r, gray.300, yellow.400, pink.200)"
          />
          <GridItem w="85%" h="100%" bg="blue.900" borderRadius={200} />
          <GridItem w="100%" h="20" bg="yellow.300" borderTopLeftRadius={200} />
          {/* part 1 */}
          <GridItem
            w="100%"
            h="20"
            bgGradient="linear(to-r, red.500, yellow.500)"
          />
          <GridItem w="90%" h="20" bg="yellow.300" borderRadius={200} />
          <GridItem
            w="100%"
            h="20"
            bg="green.500"
            borderInlineStartRadius={200}
          />
          <GridItem w="100%" h="20" bg="blue.500" />
          <GridItem
            w="90%"
            h="20"
            bgGradient="linear(to-r, blue.300, green.400, red.200)"
            borderRadius={200}
          />
          {/* part 2 */}
          <GridItem
            w="100%"
            h="20"
            bgGradient="linear(to-l, #7928CA, #FF0080)"
          />
          <GridItem
            w="100%"
            h="20"
            bgGradient={[
              "linear(to-tr, teal.300, green.400)",
              "linear(to-t, yellow.200, teal.500)",
              "linear(to-b, orange.100, blue.300)",
            ]}
          />
          <GridItem
            w="90%"
            h="20"
            bgGradient="linear(to-r, blue.500, green.500)"
            borderRadius={200}
          />
          {/* part 3 */}
          <GridItem w="100%" h="20" bg="blue.500" />
          <GridItem
            w="100%"
            h="20"
            bgGradient={[
              "linear(to-tr, teal.300, yellow.400)",
              "linear(to-t, blue.200, teal.500)",
              "linear(to-b, orange.100, purple.300)",
            ]}
            borderBottomRightRadius={50}
          />
          <GridItem w="90%" h="20" bg="blue.500" borderRadius={200} />
          {/* part 4 */}
          <GridItem
            w="100%"
            h="20"
            bgGradient="linear(to-r, green.200, pink.500)"
          />
        </Grid>
      </Grid>
      <Heading
        as="h2"
        size="xl"
        m="20"
        width="100%"
        noOfLines={2}
        textAlign={"center"}
      >
        Read Your Top Coustomer Review.
      </Heading>
      <Grid
        templateColumns={{
          base: "repeat(1, 1fr)",
          md: "repeat(2, 1fr)",
          lg: "repeat(2, 1fr)",
        }}
        gap={30}
        w="70%"
        m={"auto"}
      >
        <Cards value="https://assets.website-files.com/60819f9be381394642b5659e/6081bf0acaedecfe58dd95ad_leadiq-case-study-image.svg" />
        <Cards value="https://assets.website-files.com/60819f9be381394642b5659e/60d77c5c1f92e58f9177f933_Mavenlink-01-02.svg" />
        <Cards value="https://assets.website-files.com/60819f9be381394642b5659e/60d77d6400adb9f323bbe768_Showpad-03.svg" />
        <Cards value="https://assets.website-files.com/60819f9be381394642b5659e/62ba01eca582ccc585018918_Optimizely-card.svg" />
        <Cards value="https://assets.website-files.com/60819f9be381394642b5659e/62ba0200c08a55dfe7f49ac7_Liveperson-card.svg" />
      </Grid>
      <Fotter />
    </>
  );
}
